### PR TITLE
fix Windows completion delay

### PR DESCRIPTION
**Pull request by markonm**

### CODE REVIEW

**Comment by roxma** [comment]
Thanks for your PR!

`localhost` is more kind of a convension. `127.0.0.1` is defined in IPv4 standard. So it is always safer to use `127.0.0.1` rather than `localhost`.

Would you simply replace it with `127.0.0.1`?

**Comment by roxma** [comment]
It does get faster on my windows!

That's really wierd, any explanations? I've been searching around and haven't get a clue.

**Comment by markonm** [comment]
I'm not sure. I just profiled your code to see where delay was happening and located `self._opener.open` function. Then I looked at other tern implementations (deoplete-ternjs, and tern_for_sublime) to see how they handle that function. You can read [here](https://github.com/ternjs/tern_for_sublime/issues/57) more about similar issue. 

Do you still want me to remove `localhost`? I was afraid It might introduce breakage somewhere else.

**Comment by roxma** [comment]
I would prefer to keep it clean if it's possible.

Don't be afraid, It should work on any system confirming to IPv4 standard, and it is widely used too.

**Comment by roxma** [comment]
Thanks!

**Pull request merged**
